#!name=Zhihu去广告&优化
#!desc=移除知乎部分广告、屏蔽黑名单用户内容等

[URL Rewrite]

# === 屏蔽 / 拦截并返回空数据（对应圈X的 reject-dict / reject-200） ===

# 1) 拦截
^https?:\/\/118\.89\.204\.198 reject-200
^https?:\/\/103\.41\.167\.237 reject-200
^https?:\/\/2402:4e00:1200:ed00:0:9089:6dac:96b6 reject-200

# 2) 屏蔽下发配置
^https?:\/\/api\.zhihu\.com\/ab\/api\/v1\/products\/zhihu\/platforms\/ios\/config reject

# 3) 拦截开屏广告
^https?:\/\/api\.zhihu\.com\/commercial_api\/launch_v2\? reject-200
^https?:\/\/api\.zhihu\.com\/commercial_api\/real_time_launch_v2\? reject-200

# 4) 拦截品牌提问广告
^https?:\/\/api\.zhihu\.com\/brand\/question\/\d+\/card\? reject-200
^https?:\/\/www\.zhihu\.com\/api\/v\d+\/brand\/question\/\d+\/card\? reject-200

# 5) 去除底部标签页关注人角标
^https?:\/\/api\.zhihu\.com\/moments\/tab_v2 reject-200

# 6) 去除消息通知角标
^https?:\/\/api\.zhihu\.com\/(notifications\/v\d\/count) reject-200

# 7) 拦截回答下的卡片广告
^https?:\/\/www\.zhihu\.com\/api\/v\d\/answers\/\d+\/recommendations reject-200

# 8) 拦截应用内弹窗
^https?:\/\/api\.zhihu\.com\/me\/guides reject-200

# 9) 去除关注页最常访问
^https?:\/\/api\.zhihu\.com\/moments\/recent reject-200

# 10) 拦截推荐页顶部广告
^https?:\/\/api\.zhihu\.com\/api\/v4\/ecom_data\/config reject-200

# 11) 底栏加号的广告
^https?:\/\/api\.zhihu\.com\/content-distribution-core\/bubble\/common\/settings reject-200

# 12) 推荐页搜索栏左侧图标
^https?:\/\/api\.zhihu\.com\/feed\/render\/revisit\/current_reading reject-200

# 13) 疑似推荐页内容更新红点
^https?:\/\/api\.zhihu\.com\/feed\/render\/revisit\/tag_config reject-200

# 14) 去除回答页的相关搜索
^https?:\/\/www\.zhihu\.com\/api\/v\d+\/search\/related_queries\/answer reject-200

# 15) 暂不清楚作用
^https?:\/\/api\.zhihu\.com\/commercial_api\/banners_v3\/app_topstory_banner reject-200
^https?:\/\/api\.zhihu\.com\/ad-style-service\/request reject


[Script]

# 1) 获取用户信息 - 隔离用户数据，开启本地会员等
zhihu-people = type=http-response,pattern=^https?:\/\/api\.zhihu\.com\/people\/,requires-body=1,max-size=0,script-path=https://gist.githubusercontent.com/blackmatrix7/f5f780d0f56b319b6ad9848fd080bb18/raw/zheye.min.js

# 2) 关键词屏蔽 - 解锁本地的关键词屏蔽功能，需要开启本地VIP
zhihu-feed-root-block = type=http-response,pattern=^https?:\/\/api\.zhihu\.com\/feed-root\/block,requires-body=1,max-size=0,script-path=https://gist.githubusercontent.com/blackmatrix7/f5f780d0f56b319b6ad9848fd080bb18/raw/zheye.min.js

# 3) 优化软件配置（皮肤等）
zhihu-mcloud-config = type=http-response,pattern=^https?:\/\/m-cloud\.zhihu\.com\/api\/cloud\/config\/all\?,requires-body=1,max-size=0,script-path=https://gist.githubusercontent.com/blackmatrix7/f5f780d0f56b319b6ad9848fd080bb18/raw/zheye.min.js
zhihu-appcloud2-config = type=http-response,pattern=^https?:\/\/appcloud2\.zhihu\.com\/v\d+\/config,requires-body=1,max-size=0,script-path=https://gist.githubusercontent.com/blackmatrix7/f5f780d0f56b319b6ad9848fd080bb18/raw/zheye.min.js
zhihu-feed-render-tab-config = type=http-response,pattern=^https?:\/\/api\.zhihu\.com\/feed\/render\/tab\/config,requires-body=1,max-size=0,script-path=https://gist.githubusercontent.com/blackmatrix7/f5f780d0f56b319b6ad9848fd080bb18/raw/zheye.min.js

# 4) 用户信息 - 修改用户盐值
zhihu-user-credit-basis = type=http-response,pattern=^https?:\/\/api\.zhihu\.com\/user-credit\/basis,requires-body=1,max-size=0,script-path=https://gist.githubusercontent.com/blackmatrix7/f5f780d0f56b319b6ad9848fd080bb18/raw/zheye.min.js

# 5) 关注页 - 内容优化及屏蔽转发的黑名单用户想法
zhihu-moments-v3 = type=http-response,pattern=^https?:\/\/api\.zhihu\.com\/moments_v3\?,requires-body=1,max-size=0,script-path=https://gist.githubusercontent.com/blackmatrix7/f5f780d0f56b319b6ad9848fd080bb18/raw/zheye.min.js

# 6) 推荐页 - 移除黑名单用户发布的文章、去除广告
zhihu-topstory-recommend = type=http-response,pattern=^https?:\/\/api\.zhihu\.com\/topstory\/recommend,requires-body=1,max-size=0,script-path=https://gist.githubusercontent.com/blackmatrix7/f5f780d0f56b319b6ad9848fd080bb18/raw/zheye.min.js

# 7) 黑名单页 - 同步黑名单数据
zhihu-blocked_users = type=http-response,pattern=^https?:\/\/api\.zhihu\.com\/settings\/blocked_users,requires-body=1,max-size=0,script-path=https://gist.githubusercontent.com/blackmatrix7/f5f780d0f56b319b6ad9848fd080bb18/raw/zheye.min.js

# 8) 问题的回答列表 - 移除黑名单用户的回答、去除广告
zhihu-questions = type=http-response,pattern=^https?:\/\/api\.zhihu\.com\/(v4\/)?questions\/\\d+,requires-body=1,max-size=0,script-path=https://gist.githubusercontent.com/blackmatrix7/f5f780d0f56b319b6ad9848fd080bb18/raw/zheye.min.js

# 9) 回答信息流 - 移除黑名单用户的回答、去除广告
zhihu-next-data-bff-render = type=http-response,pattern=^https?:\/\/api\.zhihu\.com\/next-(data|bff|render),requires-body=1,max-size=0,script-path=https://gist.githubusercontent.com/blackmatrix7/f5f780d0f56b319b6ad9848fd080bb18/raw/zheye.min.js

# 10) 回答页底部评论摘要 - 移除黑名单用户发表的评论
zhihu-comment-abstract = type=http-response,pattern=^https?:\/\/www\.zhihu\.com\/api\/v4\/comment_v5\/answers\/\\d+\/abstract_comment\\?,requires-body=1,max-size=0,script-path=https://gist.githubusercontent.com/blackmatrix7/f5f780d0f56b319b6ad9848fd080bb18/raw/zheye.min.js

# 11) 评论页及子页面 - 去除黑名单用户发表的评论
zhihu-comments = type=http-response,pattern=^https?:\/\/api\.zhihu\.com\/(comment_v5\/)?(answers|comments?|articles|pins)\/\\d+\/(root_|child_)?comments?,requires-body=1,max-size=0,script-path=https://gist.githubusercontent.com/blackmatrix7/f5f780d0f56b319b6ad9848fd080bb18/raw/zheye.min.js

# 12) 消息页 - 折叠官方消息、屏蔽营销消息
zhihu-notifications = type=http-response,pattern=^https?:\/\/api\.zhihu\.com\/notifications\/v3\/(message|timeline\/entry\/system_message),requires-body=1,max-size=0,script-path=https://gist.githubusercontent.com/blackmatrix7/f5f780d0f56b319b6ad9848fd080bb18/raw/zheye.min.js

# 13) 回答页 - 内容优化，付费、营销、推广内容文首提醒
zhihu-appview-answer = type=http-response,pattern=^https?:\/\/www\.zhihu\.com\/appview\/v2\/answer\/.*(entry=(?!(preload-topstory|preload-search|preload-subscription)))?,requires-body=1,max-size=0,script-path=https://gist.githubusercontent.com/blackmatrix7/f5f780d0f56b319b6ad9848fd080bb18/raw/zheye.min.js

# 14) 回答页 - 屏蔽下翻出现的黑名单用户的回答
zhihu-next = type=http-response,pattern=^https?:\/\/api\.zhihu\.com\/next\?,requires-body=1,max-size=0,script-path=https://gist.githubusercontent.com/blackmatrix7/f5f780d0f56b319b6ad9848fd080bb18/raw/zheye.min.js

# 15) 文章页 - 去除底部广告
zhihu-articles-recommendation = type=http-response,pattern=^https?:\/\/www\.zhihu\.com\/api\/v\\d\/articles\/\\d+\/recommendation\\?,requires-body=1,max-size=0,script-path=https://gist.githubusercontent.com/blackmatrix7/f5f780d0f56b319b6ad9848fd080bb18/raw/zheye.min.js

# 16) 热榜页 - 去除广告
zhihu-hot-lists = type=http-response,pattern=^https?:\/\/api\.zhihu\.com\/topstory\/hot-lists?(\\?|\\/),requires-body=1,max-size=0,script-path=https://gist.githubusercontent.com/blackmatrix7/f5f780d0f56b319b6ad9848fd080bb18/raw/zheye.min.js

# 17) 搜索页 - 去除预置广告
zhihu-search-preset-words = type=http-response,pattern=^https?:\/\/api\.zhihu\.com\/search\/preset_words\\?,requires-body=1,max-size=0,script-path=https://gist.githubusercontent.com/blackmatrix7/f5f780d0f56b319b6ad9848fd080bb18/raw/zheye.min.js


[MITM]
hostname = 118.89.204.198,103.41.167.237,2402:4e00:1200:ed00:0:9089:6dac:96b6,www.zhihu.com,api.zhihu.com,zhuanlan.zhihu.com,appcloud2.zhihu.com,m-cloud.zhihu.com,103.41.167.236,103.41.167.234,103.41.167.235,103.41.167.226

# 说明：
# 1. 可将此内容保存为 .conf 文件后，使用小火箭导入并启用。
# 2. 如果脚本文件无效或链接失效，可尝试将 zheye.min.js 下载后放至自己可访问的地址并修改 script-path。
# 3. 部分匹配规则仅适用于特定地区及知乎 App，自行酌情调整。
