name: Update ADBlock.sgmodule

on:
  schedule:
    - cron: '0 0 * * *'  # 每天午夜运行
  workflow_dispatch:  # 允许手动触发

jobs:
  update-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # 使用内置的 GITHUB_TOKEN

      - name: Download the target file
        run: |
          curl -s -o temp.txt https://raw.githubusercontent.com/XiangwanGuan/Shadowrocket/8dd21c62533f6c027ea51c5de1e180b6b1a543ab/Module.sgmodule

      - name: Filter and update ADBlock.sgmodule
        run: |
          # 获取当前日期
          UPDATE_DATE=$(date +"%Y-%m-%d %H:%M:%S")

          # 过滤掉开头的三行和指定内容
          tail -n +4 temp.txt | grep -v 'jd_price.js =type=http-response, pattern=^https\?:\/\/in\.m\.jd\.com\/product\/graphext\/\d+\.html, script-path=https://raw.githubusercontent.com/XiangwanGuan/Shadowrocket/main/Rewrite/JavaScript/jd_price.js, requires-body=true, max-size=-1' > filtered.txt

          # 在第三行插入更新日期（带注释符号）
          head -n 2 temp.txt > header.txt
          echo "#! Updated: $UPDATE_DATE" >> header.txt
          cat header.txt filtered.txt > ADBlock.sgmodule

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add ADBlock.sgmodule
          git commit -m "Automatically updated ADBlock.sgmodule from another repository"
          git push
