name: Update ADBlock.sgmodule
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  update-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download source file
        run: |
          curl -s -O https://raw.githubusercontent.com/XiangwanGuan/Shadowrocket/8dd21c62533f6c027ea51c5de1e180b6b1a543ab/Module.sgmodule

      - name: Process file
        run: |
          # 定义更新时间
          UPDATE_DATE=$(date +"%Y-%m-%d %H:%M:%S")
          
          # 删除指定行并重建文件结构
          grep -Ev 'jd_price\.js =type=http-response, pattern=^https\?://in\.m\.jd\.com/product/graphext/\d+\.html, script-path=https://raw\.githubusercontent\.com/XiangwanGuan/Shadowrocket/main/Rewrite/JavaScript/jd_price\.js, requires-body=true, max-size=-1' Module.sgmodule |
          awk -v date="$UPDATE_DATE" '
            NR == 1 { print "!#=ADBlock"; next }
            NR == 2 { print "!#desc=去广告"; next }
            NR == 3 { print "#! Updated: " date; next }
            { print }
          ' > ADBlock.sgmodule

      - name: Commit and push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add ADBlock.sgmodule
          git commit -m "Complete file restructuring"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git push origin HEAD:main
